// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public final class CompteOuterClass {
  private CompteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Compte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Compte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoldeStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoldeStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllComptesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllComptesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllComptesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllComptesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompteByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompteByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTotalSoldeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTotalSoldeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTotalSoldeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTotalSoldeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompteByTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompteByTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveCompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveCompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveCompteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveCompteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteCompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteCompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteCompteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteCompteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014compte.proto\"T\n\006Compte\022\n\n\002id\030\001 \001(\t\022\r\n\005" +
      "solde\030\002 \001(\002\022\024\n\014dateCreation\030\003 \001(\t\022\031\n\004typ" +
      "e\030\004 \001(\0162\013.TypeCompte\"O\n\rCompteRequest\022\r\n" +
      "\005solde\030\001 \001(\002\022\024\n\014dateCreation\030\002 \001(\t\022\031\n\004ty" +
      "pe\030\003 \001(\0162\013.TypeCompte\"9\n\nSoldeStats\022\r\n\005c" +
      "ount\030\001 \001(\005\022\013\n\003sum\030\002 \001(\002\022\017\n\007average\030\003 \001(\002" +
      "\"\026\n\024GetAllComptesRequest\"1\n\025GetAllCompte" +
      "sResponse\022\030\n\007comptes\030\001 \003(\0132\007.Compte\"\"\n\024G" +
      "etCompteByIdRequest\022\n\n\002id\030\001 \001(\t\"0\n\025GetCo" +
      "mpteByIdResponse\022\027\n\006compte\030\001 \001(\0132\007.Compt" +
      "e\"\026\n\024GetTotalSoldeRequest\"3\n\025GetTotalSol" +
      "deResponse\022\032\n\005stats\030\001 \001(\0132\013.SoldeStats\"3" +
      "\n\026GetCompteByTypeRequest\022\031\n\004type\030\001 \001(\0162\013" +
      ".TypeCompte\"3\n\021SaveCompteRequest\022\036\n\006comp" +
      "te\030\001 \001(\0132\016.CompteRequest\"-\n\022SaveCompteRe" +
      "sponse\022\027\n\006compte\030\001 \001(\0132\007.Compte\"!\n\023Delet" +
      "eCompteRequest\022\n\n\002id\030\001 \001(\t\"\'\n\024DeleteComp" +
      "teResponse\022\017\n\007deleted\030\001 \001(\010*&\n\nTypeCompt" +
      "e\022\013\n\007COURANT\020\000\022\013\n\007EPARGNE\020\0012\373\002\n\rCompteSe" +
      "rvice\022;\n\nAllComptes\022\025.GetAllComptesReque" +
      "st\032\026.GetAllComptesResponse\022;\n\nCompteById" +
      "\022\025.GetCompteByIdRequest\032\026.GetCompteByIdR" +
      "esponse\022;\n\nTotalSolde\022\025.GetTotalSoldeReq" +
      "uest\032\026.GetTotalSoldeResponse\0225\n\nSaveComp" +
      "te\022\022.SaveCompteRequest\032\023.SaveCompteRespo" +
      "nse\022?\n\014CompteByType\022\027.GetCompteByTypeReq" +
      "uest\032\026.GetAllComptesResponse\022;\n\014DeleteCo" +
      "mpte\022\024.DeleteCompteRequest\032\025.DeleteCompt" +
      "eResponseB\030\n\024ma.projet.grpc.stubsP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Compte_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Compte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Compte_descriptor,
        new java.lang.String[] { "Id", "Solde", "DateCreation", "Type", });
    internal_static_CompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CompteRequest_descriptor,
        new java.lang.String[] { "Solde", "DateCreation", "Type", });
    internal_static_SoldeStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SoldeStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoldeStats_descriptor,
        new java.lang.String[] { "Count", "Sum", "Average", });
    internal_static_GetAllComptesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllComptesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllComptesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllComptesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetAllComptesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllComptesResponse_descriptor,
        new java.lang.String[] { "Comptes", });
    internal_static_GetCompteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetCompteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetCompteByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetCompteByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompteByIdResponse_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_GetTotalSoldeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetTotalSoldeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTotalSoldeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetTotalSoldeResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetTotalSoldeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTotalSoldeResponse_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_GetCompteByTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GetCompteByTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompteByTypeRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_SaveCompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_SaveCompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveCompteRequest_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_SaveCompteResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_SaveCompteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveCompteResponse_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_DeleteCompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_DeleteCompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteCompteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_DeleteCompteResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DeleteCompteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteCompteResponse_descriptor,
        new java.lang.String[] { "Deleted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
